PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL,
 password TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('ARTIST','CLIENT','BUSINESS','ADMIN')),
 suspended INTEGER NOT NULL DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY, user_id INTEGER REFERENCES users(id), expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS resets(token TEXT PRIMARY KEY,user_id INTEGER REFERENCES users(id),expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY,name TEXT UNIQUE NOT NULL,icon TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS artists (
 user_id INTEGER PRIMARY KEY REFERENCES users(id), stage_name TEXT NOT NULL, category_id INTEGER REFERENCES categories(id),
 city TEXT NOT NULL, bio TEXT DEFAULT '', genres TEXT DEFAULT '', equipment TEXT DEFAULT '', photo TEXT DEFAULT '',
 media_url TEXT DEFAULT '', rate INTEGER NOT NULL CHECK(rate>0), active INTEGER DEFAULT 0, radius INTEGER DEFAULT 25,
 verified INTEGER DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS availability (
 id INTEGER PRIMARY KEY,artist_id INTEGER REFERENCES artists(user_id),start TEXT NOT NULL,end TEXT NOT NULL,
 kind TEXT CHECK(kind IN ('AVAILABLE','BLOCKED')), CHECK(start<end)
);
CREATE TABLE IF NOT EXISTS bookings (
 id INTEGER PRIMARY KEY,client_id INTEGER REFERENCES users(id),artist_id INTEGER REFERENCES artists(user_id),
 title TEXT NOT NULL,city TEXT NOT NULL,location TEXT NOT NULL,description TEXT DEFAULT '',
 start TEXT NOT NULL,end TEXT NOT NULL,amount INTEGER CHECK(amount>0),commission INTEGER NOT NULL,
 status TEXT NOT NULL CHECK(status IN ('PENDING','COUNTER_OFFER','PAYMENT_PENDING','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED','DISPUTED','REFUNDED','PAID_OUT')),
 counter_amount INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP, CHECK(start<end)
);
CREATE INDEX IF NOT EXISTS booking_slots ON bookings(artist_id,start,end,status);
CREATE TABLE IF NOT EXISTS payments (
 id INTEGER PRIMARY KEY,booking_id INTEGER UNIQUE REFERENCES bookings(id),provider TEXT NOT NULL,
 reference TEXT UNIQUE NOT NULL,amount INTEGER NOT NULL,status TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS transactions (
 id INTEGER PRIMARY KEY,artist_id INTEGER REFERENCES artists(user_id),booking_id INTEGER UNIQUE REFERENCES bookings(id),
 kind TEXT CHECK(kind IN ('BOOKING','EXTERNAL','WITHDRAWAL')),amount INTEGER NOT NULL,commission INTEGER DEFAULT 0,
 description TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS expenses (
 id INTEGER PRIMARY KEY,artist_id INTEGER REFERENCES artists(user_id),booking_id INTEGER REFERENCES bookings(id),
 category TEXT NOT NULL,description TEXT NOT NULL,amount INTEGER CHECK(amount>0),date TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY,booking_id INTEGER REFERENCES bookings(id),sender_id INTEGER REFERENCES users(id),body TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS reviews(id INTEGER PRIMARY KEY,booking_id INTEGER UNIQUE REFERENCES bookings(id),author_id INTEGER REFERENCES users(id),artist_id INTEGER REFERENCES artists(user_id),rating INTEGER CHECK(rating BETWEEN 1 AND 5),comment TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS favorites(user_id INTEGER REFERENCES users(id),artist_id INTEGER REFERENCES artists(user_id),PRIMARY KEY(user_id,artist_id));
CREATE TABLE IF NOT EXISTS reports(id INTEGER PRIMARY KEY,author_id INTEGER REFERENCES users(id),booking_id INTEGER REFERENCES bookings(id),reason TEXT NOT NULL,target_kind TEXT DEFAULT 'BOOKING',target_id INTEGER,status TEXT DEFAULT 'OPEN',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY,user_id INTEGER REFERENCES users(id),action TEXT NOT NULL,entity_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS posts (
 id INTEGER PRIMARY KEY,artist_id INTEGER NOT NULL REFERENCES artists(user_id),caption TEXT NOT NULL,
 media_url TEXT NOT NULL,media_type TEXT NOT NULL CHECK(media_type IN ('IMAGE','VIDEO')),
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS posts_order ON posts(created_at DESC,id DESC);
CREATE TABLE IF NOT EXISTS post_likes(user_id INTEGER REFERENCES users(id),post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,PRIMARY KEY(user_id,post_id));
CREATE TABLE IF NOT EXISTS post_saves(user_id INTEGER REFERENCES users(id),post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,PRIMARY KEY(user_id,post_id));
CREATE TABLE IF NOT EXISTS follows(user_id INTEGER REFERENCES users(id),artist_id INTEGER REFERENCES artists(user_id),PRIMARY KEY(user_id,artist_id),CHECK(user_id<>artist_id));
CREATE TABLE IF NOT EXISTS post_comments(id INTEGER PRIMARY KEY,post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,author_id INTEGER REFERENCES users(id),body TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
